export const USER_REGISTRATION_REQUEST_SUCCESS = "USER_REGISTRATION_REQUEST_SUCCESS";
export const USER_REGISTRATION_REQUEST_FAIL = "USER_REGISTRATION_REQUEST_FAIL";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";
